version: "3.7"
services:
    postgres:
        container_name: postgres
        image: postgres:9.6
        environment:
            - POSTGRES_USER=etl_admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=transformations
        logging:
            options:
                max-size: 10m
                max-file: "3"